# This is a basic workflow to help you get started with Actions

name: CI/CD for Cloudhub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on VM LINUX Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Caches dependencies and build outputs to improve workflow execution time. MAVEN download LIBS
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # CH 1, uses Java 8 (24 May 2023)
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          
      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
                "id": "anypoint-exchange-v3",
                "username": "${{ secrets.ANYPOINT_USERNAME }}",
                "password": "${{ secrets.ANYPOINT_PASSWORD }}"
            }]
      - name: Deploy to CloudHub
        env:
          AUTHOR: "Pedro Diaz"
        run: |
            mvn deploy -DmuleDeploy -Dmessage="Mulesoft with Maven and Github rocks! by PDH"  -Dorg.id="90fc0d01-7a25-4ba7-9484-5fc5af720db0" -Denv="sandbox" -Dregion="us-east-2" -Ddeployment.name="Deployment-sandbox-PDH2405" -Dca.client_id="eb58d1a3df1340218f46be8b66a256f5" -Dca.client_secret="a6a75a01AE7c40938CCCc93266a5335c" 
